//! The pocketing strategy: clear the material inside a boundary with concentric
//! offset rings, in stepdown passes.
//!
//! Rings are generated by offsetting the region inward from the wall by the tool
//! radius, then by successive stepovers until it closes off. Each ring is a
//! closed cutting loop; islands (holes in the region) are honoured by the offset
//! and left standing.

use cam_cldata::Program;
use cam_geo::{offset, JoinStyle, Polygon};
use cam_model::PocketOp;

use crate::profile::depth_levels;
use crate::{CancelToken, Diagnostic, JobEnv, Strategy, StrategyResult};

/// Clears a pocket. Construct from a [`PocketOp`].
#[derive(Clone, Debug)]
pub struct PocketStrategy {
    op: PocketOp,
}

impl PocketStrategy {
    /// Build a pocketing strategy for `op`.
    pub fn new(op: PocketOp) -> Self {
        Self { op }
    }
}

impl Strategy for PocketStrategy {
    fn name(&self) -> &str {
        "pocket"
    }

    fn compute(&self, env: &JobEnv, cancel: &CancelToken) -> StrategyResult {
        let op = &self.op;
        let mut diagnostics = Vec::new();

        macro_rules! fail {
            ($($arg:tt)*) => {{
                diagnostics.push(Diagnostic::error(format!($($arg)*)));
                return StrategyResult { diagnostics, ..Default::default() };
            }};
        }

        let Some(tool) = env.tool(op.tool) else {
            fail!("operation {}: tool {} is not in the setup", op.id, op.tool);
        };
        if !op.boundary.is_valid() {
            fail!("operation {}: pocket boundary is not a closed area", op.id);
        }
        if !(0.0..1.0).contains(&op.overlap) {
            fail!("operation {}: overlap must be a fraction in [0, 1)", op.id);
        }
        if op.stepdown <= 0.0 {
            fail!("operation {}: stepdown must be positive", op.id);
        }
        // `depth` is a positive magnitude below the reference; the floor sits at Z = -depth.
        let floor = -op.depth;
        if floor >= env.heights.top_of_stock {
            diagnostics.push(Diagnostic::warning(format!(
                "operation {}: depth does not reach below the stock top; nothing to cut",
                op.id
            )));
            return StrategyResult {
                diagnostics,
                ..Default::default()
            };
        }

        let region = match Polygon::with_holes(op.boundary.clone(), op.islands.clone()) {
            Ok(p) => p,
            Err(e) => fail!("operation {}: invalid pocket region: {e}", op.id),
        };

        // Concentric rings, offsetting inward from the wall by the tool radius plus
        // the finishing allowance (so the skin is left on the boundary and every
        // island), then by the ring spacing set by the overlap.
        let r = tool.radius();
        let spacing = tool.diameter * (1.0 - op.overlap);
        if spacing <= 1e-9 {
            fail!("operation {}: overlap leaves no stepover", op.id);
        }
        let first = r + op.offset;
        let mut rings = match crate::rings::concentric_rings(&region, first, spacing, cancel) {
            Ok(rings) => rings,
            Err(crate::rings::RingsError::Cancelled) => {
                return StrategyResult {
                    diagnostics,
                    cancelled: true,
                    ..Default::default()
                };
            }
            Err(crate::rings::RingsError::Offset(e)) => {
                fail!("operation {}: offset failed: {e}", op.id)
            }
        };
        if rings.is_empty() {
            fail!(
                "operation {}: tool (⌀{}) is too large to enter the pocket",
                op.id,
                tool.diameter
            );
        }
        // `concentric_rings` yields wall-most first; reverse to carve inside-out
        // (innermost first, wall last).
        rings.reverse();

        // The cleared region the wall leads must stay inside: the region held back by
        // the wall ring's own offset. A lead-in/out that would swing past this (a
        // pocket narrower than the lead) is dropped to a plain wall pass.
        let guard = offset(std::slice::from_ref(&region), -first, JoinStyle::Round).unwrap_or_default();

        let levels = depth_levels(env.heights.top_of_stock, floor, op.stepdown);
        let mut program = Program::new();
        // Stay down within each level; only lift where the next ring is more than a
        // ring-and-a-half away (an island loop or a pinched lobe) to cut across.
        crate::rings::emit_stay_down(
            &mut program,
            &rings,
            op.start,
            op.id,
            op.feed,
            op.plunge_feed,
            op.plunge,
            op.lead_overlap,
            op.lead_in,
            op.lead_out,
            &guard,
            &env.heights,
            &levels,
            1.5 * spacing,
        );

        StrategyResult {
            program,
            diagnostics,
            cancelled: false,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use cam_cldata::{MoveKind, Step};
    use cam_geo::{Contour, Point};
    use cam_model::{Heights, Lead, Plunge, Tool, ToolKind};

    fn square(side: f64) -> Contour {
        Contour::new(vec![
            Point::new(0.0, 0.0),
            Point::new(side, 0.0),
            Point::new(side, side),
            Point::new(0.0, side),
        ])
    }

    fn tools(diameter: f64) -> Vec<Tool> {
        vec![Tool {
            number: 1,
            diameter,
            length: 30.0,
            flutes: 2,
            kind: ToolKind::EndMill,
        }]
    }

    fn plunges(result: &StrategyResult) -> usize {
        result
            .program
            .steps()
            .iter()
            .filter(|s| matches!(s, Step::Linear { tag, .. } if tag.kind == MoveKind::Plunge))
            .count()
    }

    fn retracts(result: &StrategyResult) -> usize {
        result
            .program
            .steps()
            .iter()
            .filter(|s| matches!(s, Step::Rapid { tag, .. } if tag.kind == MoveKind::Retract))
            .count()
    }

    fn cutting_moves(result: &StrategyResult) -> usize {
        result
            .program
            .steps()
            .iter()
            .filter(|s| matches!(s, Step::Linear { tag, .. } | Step::Arc { tag, .. } if tag.kind == MoveKind::Cutting))
            .count()
    }

    #[test]
    fn clears_a_square_pocket_staying_down_per_level() {
        // 40×40 pocket, ⌀8 tool, 50% overlap ⇒ 4 mm spacing, rings at 4/8/12/16.
        // Depth 3 at 1.5 stepdown ⇒ 2 levels. Staying down means one plunge and one
        // retract *per level*, not per ring — and the rings are still all cut.
        let op = PocketOp {
            clearing: cam_model::Clearing::default(),
            id: 0,
            tool: 1,
            boundary: square(40.0),
            islands: vec![],
            depth: 3.0,
            stepdown: 1.5,
            overlap: 0.5,
            offset: 0.0,
            feed: 300.0,
            plunge_feed: 100.0,
            plunge: Plunge::Straight,
            start: None,
            lead_overlap: 0.0,
            lead_in: Lead::None,
            lead_out: Lead::None,
        };
        let ts = tools(8.0);
        let env = JobEnv {
            heights: Heights::new(5.0, 2.0, 0.0),
            tools: &ts,
            stock: None,
        };
        let result = PocketStrategy::new(op).compute(&env, &CancelToken::new());
        assert!(!result.has_errors(), "{:?}", result.diagnostics);
        assert_eq!(plunges(&result), 2, "one entry plunge per level");
        assert_eq!(retracts(&result), 2, "one retract per level");
        assert!(
            cutting_moves(&result) > 8,
            "all rings are still cut at each level"
        );
    }

    #[test]
    fn helix_plunge_pocket_enters_on_helical_arcs() {
        let op = PocketOp {
            clearing: cam_model::Clearing::default(),
            id: 0,
            tool: 1,
            boundary: square(40.0),
            islands: vec![],
            depth: 3.0,
            stepdown: 1.5,
            overlap: 0.5,
            offset: 0.0,
            feed: 300.0,
            plunge_feed: 100.0,
            plunge: Plunge::Helix {
                radius: 1.0,
                pitch: 0.5,
            },
            start: None,
            lead_overlap: 0.0,
            lead_in: Lead::None,
            lead_out: Lead::None,
        };
        let ts = tools(8.0);
        let env = JobEnv {
            heights: Heights::new(5.0, 2.0, 0.0),
            tools: &ts,
            stock: None,
        };
        let result = PocketStrategy::new(op).compute(&env, &CancelToken::new());
        assert!(!result.has_errors(), "{:?}", result.diagnostics);
        // The straight-plunge linears are replaced by (Plunge-tagged) helix arcs.
        assert_eq!(
            plunges(&result),
            0,
            "no straight plunges with a helix entry"
        );
        let plunge_arcs: Vec<f64> = result
            .program
            .steps()
            .iter()
            .filter_map(|s| match s {
                Step::Arc { tag, end, .. } if tag.kind == MoveKind::Plunge => Some(end.z),
                _ => None,
            })
            .collect();
        assert!(!plunge_arcs.is_empty(), "expected helix plunge arcs");
        // The helix descends: at least one arc ends below the stock top.
        assert!(plunge_arcs.iter().any(|&z| z < 0.0), "helix must descend");
    }

    #[test]
    fn tool_too_large_for_pocket_errors() {
        let op = PocketOp {
            clearing: cam_model::Clearing::default(),
            id: 0,
            tool: 1,
            boundary: square(10.0),
            islands: vec![],
            depth: 3.0,
            stepdown: 1.5,
            overlap: 0.5,
            offset: 0.0,
            feed: 300.0,
            plunge_feed: 100.0,
            plunge: Plunge::Straight,
            start: None,
            lead_overlap: 0.0,
            lead_in: Lead::None,
            lead_out: Lead::None,
        };
        let ts = tools(12.0); // radius 6 > half of 10 ⇒ cannot enter
        let env = JobEnv {
            heights: Heights::new(5.0, 2.0, 0.0),
            tools: &ts,
            stock: None,
        };
        let result = PocketStrategy::new(op).compute(&env, &CancelToken::new());
        assert!(result.has_errors());
        assert!(result.program.is_empty());
    }

    /// Each ring's straight plunge (at its start) and the retract that follows it,
    /// paired in emission order.
    fn max_cutting_x(result: &StrategyResult) -> f64 {
        result
            .program
            .steps()
            .iter()
            .filter_map(|s| match s {
                Step::Linear { to, tag, .. } if tag.kind == MoveKind::Cutting => Some(to.x),
                Step::Arc { end, tag, .. } if tag.kind == MoveKind::Cutting => Some(end.x),
                _ => None,
            })
            .fold(f64::MIN, f64::max)
    }

    #[test]
    fn overlap_sets_the_ring_spacing() {
        // Finer overlap ⇒ smaller spacing ⇒ more rings ⇒ more cutting moves.
        let run = |overlap: f64| {
            let mut op = PocketOp {
                clearing: cam_model::Clearing::default(),
                id: 0,
                tool: 1,
                boundary: square(40.0),
                islands: vec![],
                depth: 1.5,
                stepdown: 1.5,
                overlap,
                offset: 0.0,
                feed: 300.0,
                plunge_feed: 100.0,
                plunge: Plunge::Straight,
                start: None,
                lead_overlap: 0.0,
                lead_in: Lead::None,
                lead_out: Lead::None,
            };
            op.overlap = overlap;
            let ts = tools(8.0);
            let env = JobEnv {
                heights: Heights::new(5.0, 2.0, 0.0),
                tools: &ts,
                stock: None,
            };
            let r = PocketStrategy::new(op).compute(&env, &CancelToken::new());
            assert!(!r.has_errors(), "{:?}", r.diagnostics);
            cutting_moves(&r)
        };
        assert!(run(0.75) > run(0.25), "more overlap ⇒ tighter spacing ⇒ more rings");
    }

    #[test]
    fn offset_leaves_a_skin_on_the_wall() {
        // A 2 mm finishing offset keeps the outermost (wall) ring 2 mm inside the
        // boundary, so the deepest cut into the +X wall is 2 mm shallower.
        let run = |offset: f64| {
            let op = PocketOp {
                clearing: cam_model::Clearing::default(),
                id: 0,
                tool: 1,
                boundary: square(40.0),
                islands: vec![],
                depth: 1.5,
                stepdown: 1.5,
                overlap: 0.5,
                offset,
                feed: 300.0,
                plunge_feed: 100.0,
                plunge: Plunge::Straight,
                start: None,
                lead_overlap: 0.0,
                lead_in: Lead::None,
                lead_out: Lead::None,
            };
            let ts = tools(8.0);
            let env = JobEnv {
                heights: Heights::new(5.0, 2.0, 0.0),
                tools: &ts,
                stock: None,
            };
            let r = PocketStrategy::new(op).compute(&env, &CancelToken::new());
            assert!(!r.has_errors(), "{:?}", r.diagnostics);
            max_cutting_x(&r)
        };
        let base = run(0.0);
        let skinned = run(2.0);
        assert!(
            (base - skinned - 2.0).abs() < 1e-6,
            "a 2 mm offset holds the wall ring 2 mm back ({base} vs {skinned})"
        );
    }

    /// Every lead-in/out arc as `(start, end)` — start is the position before it.
    fn leadin_arcs(result: &StrategyResult) -> Vec<(Point, Point)> {
        let mut pos = Point::new(0.0, 0.0);
        let mut arcs = Vec::new();
        for s in result.program.steps() {
            match s {
                Step::Rapid { to, .. } | Step::Linear { to, .. } => pos = Point::new(to.x, to.y),
                Step::Arc { end, tag, .. } => {
                    if tag.kind == MoveKind::LeadIn {
                        arcs.push((pos, Point::new(end.x, end.y)));
                    }
                    pos = Point::new(end.x, end.y);
                }
                _ => {}
            }
        }
        arcs
    }

    fn leaded_op(islands: Vec<Contour>) -> PocketOp {
        PocketOp {
            clearing: cam_model::Clearing::default(),
            id: 0,
            tool: 1,
            boundary: square(40.0),
            islands,
            depth: 1.5,
            stepdown: 1.5,
            overlap: 0.5,
            offset: 0.0,
            feed: 300.0,
            plunge_feed: 100.0,
            plunge: Plunge::Straight,
            start: None,
            lead_overlap: 0.0,
            lead_in: Lead::Arc { radius: 2.0 },
            lead_out: Lead::Arc { radius: 2.0 },
        }
    }

    #[test]
    fn wall_leads_ease_onto_the_boundary_from_inside() {
        let ts = tools(8.0);
        let env = JobEnv {
            heights: Heights::new(5.0, 2.0, 0.0),
            tools: &ts,
            stock: None,
        };
        let result = PocketStrategy::new(leaded_op(vec![])).compute(&env, &CancelToken::new());
        assert!(!result.has_errors(), "{:?}", result.diagnostics);
        let arcs = leadin_arcs(&result);
        assert_eq!(arcs.len(), 2, "one lead-in + one lead-out on the single boundary wall");
        // The lead-in comes from the cleared interior: its entry is closer to the
        // pocket centre (20,20) than the wall point it eases onto.
        let (entry, wall) = arcs[0];
        let d = |p: Point| (p.x - 20.0).hypot(p.y - 20.0);
        assert!(
            d(entry) < d(wall),
            "lead-in must ease in from inside, entry {:?} wall {:?}",
            (entry.x, entry.y),
            (wall.x, wall.y)
        );

        // No leads emitted when unset.
        let mut plain = leaded_op(vec![]);
        plain.lead_in = Lead::None;
        plain.lead_out = Lead::None;
        let r2 = PocketStrategy::new(plain).compute(&env, &CancelToken::new());
        assert!(leadin_arcs(&r2).is_empty(), "no leads when unset");
    }

    #[test]
    fn a_lead_too_big_for_the_pocket_is_dropped_not_overshot() {
        // A 10×10 pocket with a ⌀6 tool clears to a 4×4 wall ring — only 2 mm of
        // room from that wall to the centre. A radius-3 arc lead cannot fit without
        // swinging past the far wall, so it must be dropped to a plain pass (no lead
        // arc), never emitted overshooting the boundary. High overlap gives the
        // multiple rings that put the wall ring on the leaded path in the first place.
        let small = PocketOp {
            clearing: cam_model::Clearing::default(),
            id: 0,
            tool: 1,
            boundary: square(10.0),
            islands: vec![],
            depth: 1.5,
            stepdown: 1.5,
            overlap: 0.9,
            offset: 0.0,
            feed: 300.0,
            plunge_feed: 100.0,
            plunge: Plunge::Straight,
            start: None,
            lead_overlap: 0.0,
            lead_in: Lead::Arc { radius: 3.0 },
            lead_out: Lead::Arc { radius: 3.0 },
        };
        let ts = tools(6.0);
        let env = JobEnv {
            heights: Heights::new(5.0, 2.0, 0.0),
            tools: &ts,
            stock: None,
        };
        let result = PocketStrategy::new(small).compute(&env, &CancelToken::new());
        assert!(!result.has_errors(), "{:?}", result.diagnostics);
        assert!(
            leadin_arcs(&result).is_empty(),
            "an oversized lead must be dropped, not emitted past the wall: {:?}",
            leadin_arcs(&result)
        );

        // Every emitted cut stays inside the pocket boundary [0,10]² (no overshoot).
        for s in result.program.steps() {
            let p = match s {
                Step::Linear { to, tag, .. } if tag.kind == MoveKind::Cutting => Some((to.x, to.y)),
                Step::Arc { end, tag, .. } if tag.kind == MoveKind::Cutting => Some((end.x, end.y)),
                _ => None,
            };
            if let Some((x, y)) = p {
                assert!(
                    (-1e-6..=10.0 + 1e-6).contains(&x) && (-1e-6..=10.0 + 1e-6).contains(&y),
                    "cut left the pocket at ({x}, {y})"
                );
            }
        }
    }

    #[test]
    fn wall_leads_reach_islands_without_gouging() {
        // A centred 8×8 island: both the boundary and the island wall get leads,
        // and no lead cuts into the island material [16,24] (verifies the lead sits
        // on the pocket side of the island, i.e. the winding is read correctly).
        let island = Contour::new(vec![
            Point::new(16.0, 16.0),
            Point::new(24.0, 16.0),
            Point::new(24.0, 24.0),
            Point::new(16.0, 24.0),
        ]);
        let ts = tools(6.0);
        let env = JobEnv {
            heights: Heights::new(5.0, 2.0, 0.0),
            tools: &ts,
            stock: None,
        };
        let result =
            PocketStrategy::new(leaded_op(vec![island])).compute(&env, &CancelToken::new());
        assert!(!result.has_errors(), "{:?}", result.diagnostics);
        let arcs = leadin_arcs(&result);
        assert_eq!(arcs.len(), 4, "leads on the boundary and the island (2 each)");
        for (entry, _) in &arcs {
            let into_island = entry.x > 16.0 && entry.x < 24.0 && entry.y > 16.0 && entry.y < 24.0;
            assert!(
                !into_island,
                "a lead cut into the island, entry ({}, {})",
                entry.x, entry.y
            );
        }
    }
}
