//! The pocketing strategy: clear the material inside a boundary with concentric
//! offset rings, in stepdown passes.
//!
//! Rings are generated by offsetting the region inward from the wall by the tool
//! radius, then by successive stepovers until it closes off. Each ring is a
//! closed cutting loop; islands (holes in the region) are honoured by the offset
//! and left standing.

use cam_cldata::{MoveKind, Point3, Program, Step, Tag};
use cam_geo::{offset, JoinStyle, Point, Polygon};
use cam_model::{Heights, PocketOp};

use crate::profile::depth_levels;
use crate::{CancelToken, Diagnostic, JobEnv, Strategy, StrategyResult};

/// Safety cap on the number of concentric rings (guards the offset loop).
const MAX_RINGS: usize = 100_000;

/// Clears a pocket. Construct from a [`PocketOp`].
#[derive(Clone, Debug)]
pub struct PocketStrategy {
    op: PocketOp,
}

impl PocketStrategy {
    /// Build a pocketing strategy for `op`.
    pub fn new(op: PocketOp) -> Self {
        Self { op }
    }
}

impl Strategy for PocketStrategy {
    fn name(&self) -> &str {
        "pocket"
    }

    fn compute(&self, env: &JobEnv, cancel: &CancelToken) -> StrategyResult {
        let op = &self.op;
        let mut diagnostics = Vec::new();

        macro_rules! fail {
            ($($arg:tt)*) => {{
                diagnostics.push(Diagnostic::error(format!($($arg)*)));
                return StrategyResult { diagnostics, ..Default::default() };
            }};
        }

        let Some(tool) = env.tool(op.tool) else {
            fail!("operation {}: tool {} is not in the setup", op.id, op.tool);
        };
        if !op.boundary.is_valid() {
            fail!("operation {}: pocket boundary is not a closed area", op.id);
        }
        if op.stepover <= 0.0 || op.stepdown <= 0.0 {
            fail!(
                "operation {}: stepover and stepdown must be positive",
                op.id
            );
        }
        if op.depth >= env.heights.top_of_stock {
            diagnostics.push(Diagnostic::warning(format!(
                "operation {}: depth is at or above the stock top; nothing to cut",
                op.id
            )));
            return StrategyResult {
                diagnostics,
                ..Default::default()
            };
        }

        let region = match Polygon::with_holes(op.boundary.clone(), op.islands.clone()) {
            Ok(p) => p,
            Err(e) => fail!("operation {}: invalid pocket region: {e}", op.id),
        };

        // Concentric rings, offsetting inward from the wall.
        let r = tool.radius();
        let mut rings: Vec<Vec<Point>> = Vec::new();
        let mut d = r;
        loop {
            if cancel.is_cancelled() {
                return StrategyResult {
                    diagnostics,
                    cancelled: true,
                    ..Default::default()
                };
            }
            let offsets = match offset(std::slice::from_ref(&region), -d, JoinStyle::Round) {
                Ok(v) => v,
                Err(e) => fail!("operation {}: offset failed: {e}", op.id),
            };
            if offsets.is_empty() {
                break;
            }
            for poly in &offsets {
                rings.push(poly.outer().points().to_vec());
                for hole in poly.holes() {
                    rings.push(hole.points().to_vec());
                }
            }
            d += op.stepover;
            if rings.len() > MAX_RINGS {
                break;
            }
        }
        if rings.is_empty() {
            fail!(
                "operation {}: tool (⌀{}) is too large to enter the pocket",
                op.id,
                tool.diameter
            );
        }

        let levels = depth_levels(env.heights.top_of_stock, op.depth, op.stepdown);
        let mut program = Program::new();
        for &z in &levels {
            if cancel.is_cancelled() {
                return StrategyResult {
                    program,
                    diagnostics,
                    cancelled: true,
                };
            }
            for ring in &rings {
                emit_ring(&mut program, ring, op, &env.heights, z);
            }
        }

        StrategyResult {
            program,
            diagnostics,
            cancelled: false,
        }
    }
}

/// Emit approach, plunge, one closed cutting loop, and retract for a ring at `z`.
fn emit_ring(prog: &mut Program, pts: &[Point], op: &PocketOp, h: &Heights, z: f64) {
    if pts.len() < 3 {
        return;
    }
    let start = pts[0];
    let link = Tag::new(op.id, MoveKind::Link);
    let plunge = Tag::new(op.id, MoveKind::Plunge);
    let cut = Tag::new(op.id, MoveKind::Cutting);
    let retract = Tag::new(op.id, MoveKind::Retract);

    prog.push(Step::Rapid {
        to: Point3::new(start.x, start.y, h.clearance),
        tag: link,
    });
    prog.push(Step::Rapid {
        to: Point3::new(start.x, start.y, h.top_of_stock),
        tag: link,
    });
    prog.push(Step::Linear {
        to: Point3::new(start.x, start.y, z),
        feed: op.plunge_feed,
        tag: plunge,
    });
    crate::emit::cut_loop(prog, pts, op.feed, cut, z);
    prog.push(Step::Rapid {
        to: Point3::new(start.x, start.y, h.clearance),
        tag: retract,
    });
}

#[cfg(test)]
mod tests {
    use super::*;
    use cam_cldata::MoveKind;
    use cam_geo::Contour;
    use cam_model::{Tool, ToolKind};

    fn square(side: f64) -> Contour {
        Contour::new(vec![
            Point::new(0.0, 0.0),
            Point::new(side, 0.0),
            Point::new(side, side),
            Point::new(0.0, side),
        ])
    }

    fn tools(diameter: f64) -> Vec<Tool> {
        vec![Tool {
            number: 1,
            diameter,
            length: 30.0,
            flutes: 2,
            kind: ToolKind::EndMill,
        }]
    }

    fn plunges(result: &StrategyResult) -> usize {
        result
            .program
            .steps()
            .iter()
            .filter(|s| matches!(s, Step::Linear { tag, .. } if tag.kind == MoveKind::Plunge))
            .count()
    }

    #[test]
    fn clears_a_square_pocket_in_concentric_rings() {
        // 40×40 pocket, ⌀8 tool, 4 mm stepover: rings at inward offsets 4/8/12/16
        // (offset 20 closes it off) ⇒ 4 rings. Depth −3 at 1.5 stepdown ⇒ 2
        // levels. One plunge per ring per level ⇒ 8.
        let op = PocketOp {
            id: 0,
            tool: 1,
            boundary: square(40.0),
            islands: vec![],
            depth: -3.0,
            stepdown: 1.5,
            stepover: 4.0,
            feed: 300.0,
            plunge_feed: 100.0,
        };
        let ts = tools(8.0);
        let env = JobEnv {
            heights: Heights::new(5.0, 2.0, 0.0),
            tools: &ts,
        };
        let result = PocketStrategy::new(op).compute(&env, &CancelToken::new());
        assert!(!result.has_errors(), "{:?}", result.diagnostics);
        assert_eq!(plunges(&result), 8, "4 rings × 2 depth levels");
    }

    #[test]
    fn tool_too_large_for_pocket_errors() {
        let op = PocketOp {
            id: 0,
            tool: 1,
            boundary: square(10.0),
            islands: vec![],
            depth: -3.0,
            stepdown: 1.5,
            stepover: 4.0,
            feed: 300.0,
            plunge_feed: 100.0,
        };
        let ts = tools(12.0); // radius 6 > half of 10 ⇒ cannot enter
        let env = JobEnv {
            heights: Heights::new(5.0, 2.0, 0.0),
            tools: &ts,
        };
        let result = PocketStrategy::new(op).compute(&env, &CancelToken::new());
        assert!(result.has_errors());
        assert!(result.program.is_empty());
    }
}
