//! The pocketing strategy: clear the material inside a boundary with concentric
//! offset rings, in stepdown passes.
//!
//! Rings are generated by offsetting the region inward from the wall by the tool
//! radius, then by successive stepovers until it closes off. Each ring is a
//! closed cutting loop; islands (holes in the region) are honoured by the offset
//! and left standing.

use cam_cldata::{MoveKind, Point3, Program, Step, Tag};
use cam_geo::{offset, JoinStyle, Point, Polygon};
use cam_model::{Heights, PocketOp};

use crate::profile::depth_levels;
use crate::{CancelToken, Diagnostic, JobEnv, Strategy, StrategyResult};

/// Safety cap on the number of concentric rings (guards the offset loop).
const MAX_RINGS: usize = 100_000;

/// Clears a pocket. Construct from a [`PocketOp`].
#[derive(Clone, Debug)]
pub struct PocketStrategy {
    op: PocketOp,
}

impl PocketStrategy {
    /// Build a pocketing strategy for `op`.
    pub fn new(op: PocketOp) -> Self {
        Self { op }
    }
}

impl Strategy for PocketStrategy {
    fn name(&self) -> &str {
        "pocket"
    }

    fn compute(&self, env: &JobEnv, cancel: &CancelToken) -> StrategyResult {
        let op = &self.op;
        let mut diagnostics = Vec::new();

        macro_rules! fail {
            ($($arg:tt)*) => {{
                diagnostics.push(Diagnostic::error(format!($($arg)*)));
                return StrategyResult { diagnostics, ..Default::default() };
            }};
        }

        let Some(tool) = env.tool(op.tool) else {
            fail!("operation {}: tool {} is not in the setup", op.id, op.tool);
        };
        if !op.boundary.is_valid() {
            fail!("operation {}: pocket boundary is not a closed area", op.id);
        }
        if op.stepover <= 0.0 || op.stepdown <= 0.0 {
            fail!(
                "operation {}: stepover and stepdown must be positive",
                op.id
            );
        }
        if op.depth >= env.heights.top_of_stock {
            diagnostics.push(Diagnostic::warning(format!(
                "operation {}: depth is at or above the stock top; nothing to cut",
                op.id
            )));
            return StrategyResult {
                diagnostics,
                ..Default::default()
            };
        }

        let region = match Polygon::with_holes(op.boundary.clone(), op.islands.clone()) {
            Ok(p) => p,
            Err(e) => fail!("operation {}: invalid pocket region: {e}", op.id),
        };

        // Concentric rings, offsetting inward from the wall.
        let r = tool.radius();
        let mut rings: Vec<Vec<Point>> = Vec::new();
        let mut d = r;
        loop {
            if cancel.is_cancelled() {
                return StrategyResult {
                    diagnostics,
                    cancelled: true,
                    ..Default::default()
                };
            }
            let offsets = match offset(std::slice::from_ref(&region), -d, JoinStyle::Round) {
                Ok(v) => v,
                Err(e) => fail!("operation {}: offset failed: {e}", op.id),
            };
            if offsets.is_empty() {
                break;
            }
            for poly in &offsets {
                rings.push(poly.outer().points().to_vec());
                for hole in poly.holes() {
                    rings.push(hole.points().to_vec());
                }
            }
            d += op.stepover;
            if rings.len() > MAX_RINGS {
                break;
            }
        }
        if rings.is_empty() {
            fail!(
                "operation {}: tool (⌀{}) is too large to enter the pocket",
                op.id,
                tool.diameter
            );
        }

        let levels = depth_levels(env.heights.top_of_stock, op.depth, op.stepdown);
        let mut program = Program::new();
        for &z in &levels {
            if cancel.is_cancelled() {
                return StrategyResult {
                    program,
                    diagnostics,
                    cancelled: true,
                };
            }
            for ring in &rings {
                // Begin each ring near the operator's chosen lead-in point, so the
                // plunge/entry witness marks line up there; `None` keeps the default.
                let rotated = crate::profile::rotate_to_start(ring, op.start);
                emit_ring(&mut program, &rotated, op, &env.heights, z);
            }
        }

        StrategyResult {
            program,
            diagnostics,
            cancelled: false,
        }
    }
}

/// Emit approach, plunge, one closed cutting loop, and retract for a ring at `z`.
/// The entry uses the operation's plunge strategy (helix/ramp descend toward the
/// pocket interior, staying clear of the wall).
fn emit_ring(prog: &mut Program, pts: &[Point], op: &PocketOp, h: &Heights, z: f64) {
    if pts.len() < 3 {
        return;
    }
    let start = pts[0];
    let link = Tag::new(op.id, MoveKind::Link);
    let plunge = Tag::new(op.id, MoveKind::Plunge);
    let cut = Tag::new(op.id, MoveKind::Cutting);
    let retract = Tag::new(op.id, MoveKind::Retract);

    prog.push(Step::Rapid {
        to: Point3::new(start.x, start.y, h.clearance),
        tag: link,
    });
    prog.push(Step::Rapid {
        to: Point3::new(start.x, start.y, h.top_of_stock),
        tag: link,
    });
    // Descend into the material per the plunge strategy. A helix/ramp is placed on
    // the *inward* side of the ring so it stays within the pocket, not the wall.
    let tan = crate::profile::start_tangent(pts);
    let out = crate::profile::outward_normal(pts);
    crate::profile::emit_plunge(
        prog,
        start,
        tan,
        (-out.0, -out.1),
        h.top_of_stock,
        z,
        op.plunge,
        op.plunge_feed,
        op.feed,
        plunge,
    );
    // Cut the ring, keeping on past the start by `lead_overlap` to re-machine the
    // plunge/closure witness, then retract from wherever the overlap ended (the
    // start itself when the overlap is zero — byte-identical to before).
    let (loop_pts, exit_pt, _tan) = crate::emit::loop_with_overlap(pts, op.lead_overlap);
    crate::emit::cut_polyline(prog, &loop_pts, op.feed, cut, z);
    prog.push(Step::Rapid {
        to: Point3::new(exit_pt.x, exit_pt.y, h.clearance),
        tag: retract,
    });
}

#[cfg(test)]
mod tests {
    use super::*;
    use cam_cldata::MoveKind;
    use cam_geo::Contour;
    use cam_model::{Plunge, Tool, ToolKind};

    fn square(side: f64) -> Contour {
        Contour::new(vec![
            Point::new(0.0, 0.0),
            Point::new(side, 0.0),
            Point::new(side, side),
            Point::new(0.0, side),
        ])
    }

    fn tools(diameter: f64) -> Vec<Tool> {
        vec![Tool {
            number: 1,
            diameter,
            length: 30.0,
            flutes: 2,
            kind: ToolKind::EndMill,
        }]
    }

    fn plunges(result: &StrategyResult) -> usize {
        result
            .program
            .steps()
            .iter()
            .filter(|s| matches!(s, Step::Linear { tag, .. } if tag.kind == MoveKind::Plunge))
            .count()
    }

    #[test]
    fn clears_a_square_pocket_in_concentric_rings() {
        // 40×40 pocket, ⌀8 tool, 4 mm stepover: rings at inward offsets 4/8/12/16
        // (offset 20 closes it off) ⇒ 4 rings. Depth −3 at 1.5 stepdown ⇒ 2
        // levels. One plunge per ring per level ⇒ 8.
        let op = PocketOp {
            id: 0,
            tool: 1,
            boundary: square(40.0),
            islands: vec![],
            depth: -3.0,
            stepdown: 1.5,
            stepover: 4.0,
            feed: 300.0,
            plunge_feed: 100.0,
            plunge: Plunge::Straight,
            start: None,
            lead_overlap: 0.0,
        };
        let ts = tools(8.0);
        let env = JobEnv {
            heights: Heights::new(5.0, 2.0, 0.0),
            tools: &ts,
        };
        let result = PocketStrategy::new(op).compute(&env, &CancelToken::new());
        assert!(!result.has_errors(), "{:?}", result.diagnostics);
        assert_eq!(plunges(&result), 8, "4 rings × 2 depth levels");
    }

    #[test]
    fn helix_plunge_pocket_enters_on_helical_arcs() {
        let op = PocketOp {
            id: 0,
            tool: 1,
            boundary: square(40.0),
            islands: vec![],
            depth: -3.0,
            stepdown: 1.5,
            stepover: 4.0,
            feed: 300.0,
            plunge_feed: 100.0,
            plunge: Plunge::Helix {
                radius: 1.0,
                pitch: 0.5,
            },
            start: None,
            lead_overlap: 0.0,
        };
        let ts = tools(8.0);
        let env = JobEnv {
            heights: Heights::new(5.0, 2.0, 0.0),
            tools: &ts,
        };
        let result = PocketStrategy::new(op).compute(&env, &CancelToken::new());
        assert!(!result.has_errors(), "{:?}", result.diagnostics);
        // The straight-plunge linears are replaced by (Plunge-tagged) helix arcs.
        assert_eq!(
            plunges(&result),
            0,
            "no straight plunges with a helix entry"
        );
        let plunge_arcs: Vec<f64> = result
            .program
            .steps()
            .iter()
            .filter_map(|s| match s {
                Step::Arc { tag, end, .. } if tag.kind == MoveKind::Plunge => Some(end.z),
                _ => None,
            })
            .collect();
        assert!(!plunge_arcs.is_empty(), "expected helix plunge arcs");
        // The helix descends: at least one arc ends below the stock top.
        assert!(plunge_arcs.iter().any(|&z| z < 0.0), "helix must descend");
    }

    #[test]
    fn tool_too_large_for_pocket_errors() {
        let op = PocketOp {
            id: 0,
            tool: 1,
            boundary: square(10.0),
            islands: vec![],
            depth: -3.0,
            stepdown: 1.5,
            stepover: 4.0,
            feed: 300.0,
            plunge_feed: 100.0,
            plunge: Plunge::Straight,
            start: None,
            lead_overlap: 0.0,
        };
        let ts = tools(12.0); // radius 6 > half of 10 ⇒ cannot enter
        let env = JobEnv {
            heights: Heights::new(5.0, 2.0, 0.0),
            tools: &ts,
        };
        let result = PocketStrategy::new(op).compute(&env, &CancelToken::new());
        assert!(result.has_errors());
        assert!(result.program.is_empty());
    }

    /// Each ring's straight plunge (at its start) and the retract that follows it,
    /// paired in emission order.
    fn plunge_retract_pairs(result: &StrategyResult) -> Vec<(Point3, Point3)> {
        let mut pairs = Vec::new();
        let mut pending: Option<Point3> = None;
        for s in result.program.steps() {
            match s {
                Step::Linear { to, tag, .. } if tag.kind == MoveKind::Plunge => pending = Some(*to),
                Step::Rapid { to, tag } if tag.kind == MoveKind::Retract => {
                    if let Some(p) = pending.take() {
                        pairs.push((p, *to));
                    }
                }
                _ => {}
            }
        }
        pairs
    }

    fn pocket_op(lead_overlap: f64) -> PocketOp {
        PocketOp {
            id: 0,
            tool: 1,
            boundary: square(40.0),
            islands: vec![],
            depth: -1.5,
            stepdown: 1.5,
            stepover: 4.0,
            feed: 300.0,
            plunge_feed: 100.0,
            plunge: Plunge::Straight,
            start: None,
            lead_overlap,
        }
    }

    #[test]
    fn zero_overlap_closes_each_ring_at_its_start() {
        let env = JobEnv {
            heights: Heights::new(5.0, 2.0, 0.0),
            tools: &tools(8.0),
        };
        let result = PocketStrategy::new(pocket_op(0.0)).compute(&env, &CancelToken::new());
        let pairs = plunge_retract_pairs(&result);
        assert!(!pairs.is_empty());
        for (plunge, retract) in pairs {
            assert!(
                (plunge.x - retract.x).abs() < 1e-9 && (plunge.y - retract.y).abs() < 1e-9,
                "with no overlap the ring retracts exactly where it plunged"
            );
        }
    }

    #[test]
    fn overlap_retracts_each_ring_past_its_start() {
        let overlap = 2.0;
        let env = JobEnv {
            heights: Heights::new(5.0, 2.0, 0.0),
            tools: &tools(8.0),
        };
        let result = PocketStrategy::new(pocket_op(overlap)).compute(&env, &CancelToken::new());
        let pairs = plunge_retract_pairs(&result);
        assert!(!pairs.is_empty());
        for (plunge, retract) in pairs {
            let d = ((retract.x - plunge.x).powi(2) + (retract.y - plunge.y).powi(2)).sqrt();
            // Moved off the start, by no more than the overlap arc-length (a chord
            // on a rounded corner can be a touch shorter, never longer).
            assert!(
                d > 1e-6 && d <= overlap + 1e-6,
                "ring should retract past its start by up to {overlap} mm, got {d}"
            );
        }
    }
}
